[[redirects]]
  from = "/api/*"
  to = "https://api.tempdomain.store/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/lipsync/*"
  to = "https://lipsync.tempdomain.store/lipsync/:splat"
  status = 200
  force = true